#! /bin/bash

flg=$1
user=$(whoami)

if [[ "$user" == "spanish user" ]]; then 
	menuname="Ir";
elif [[ "$user" == "french user" ]]; then
 	menuname="Aller"; 
elif [[ "$user" == "italian user" ]]; then
	menuname="Vai";
else {
	echo "Who the fuck are you?";
	exit; 
}
fi

if [[ -z "$flg" ]]; then
	echo " ";
	echo "airdrop: prepare your mac to recieve via AirDrop";
	echo " Useage:";
	echo " $ airdrop 1 ( turns on wifi and bluetooth, opens ~/Downloads in Finder )";
	echo " $ airdrop 0 ( turns off just bluetooth, because I'm guessing you're always online )";
	echo " ";
elif [[ "$flg" == 1 ]]; then
	networksetup -setairportpower en1 on;
	blueutil -p 1 -d 1;
	osascript -e "
  tell application \"Finder\"
		activate
		tell application \"System Events\" to keystroke \"R\" using {command down, shift down}
  end tell ";
	open /Users/"$user"/Downloads;
	echo " ";
	echo "AirDrop Ready!";
	echo " ";
elif [[ "$flg" == 0 ]]; then
	blueutil -d 0 -p 0;
	echo " ";
	echo "AirDrop off (bluetooth off)";
	echo " ";
else {
	echo " ";
	echo "Error, invalid option";
	echo " ";
}
fi
